# Use the base image of Ubuntu
FROM ubuntu:20.04

# Set the working directory inside the container
WORKDIR /app

# Install curl, Node.js, npm, and other dependencies
RUN apt-get update && apt-get install -y curl gnupg2 build-essential \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Install the Angular CLI globally
RUN npm install -g @angular/cli

# Copy the package.json and package-lock.json files from the root frontend directory to the working directory
COPY ../../frontend/package.json ../../frontend/package-lock.json ./

# Install the project dependencies
RUN npm install --legacy-peer-deps

# Copy the entire frontend project into the container
COPY ../../frontend /app

# Expose the port that the Angular app will use
EXPOSE 4200

# Command to run the Angular application in development mode
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
