# ============================================================================
# @Author: Ramiro Luiz Nunes
# @Date:   2024-06-29 16:44:04
# @Info:   Docker compose for managing containers for the PAC-MAN website
# ============================================================================

version: '3.9'

services:
  backend:
    image: pacman-backend:0.1.0
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    container_name: pacman-backend
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: pacman-frontend:0.1.0
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    container_name: pacman-frontend
    volumes:
      - ../frontend:/app
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: pacman-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pacman
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
