# ============================================================================
# @Author: Ramiro Luiz Nunes
# @Date:   2024-06-30 20:04:51
# @Info:   Docker compose to manage DB containers for the PAC-MAN site
# ============================================================================

version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pacman-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pacman
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: pacman-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
